### ISSUE TITLE
Deep-dive to understand the conceptual components of proposed architecture

### ISSUE THREAD

**Issue by konoikon** [DZhangLab/HIDe-infrastructure#16]
# Summary
Deep-dive into the proposed architecture, analyze every component and compile it into a writeup.

# To-do List
- [ ] Bullet points of core components
- [ ] Algorithms that can be used for the Root CA (advantages and disadvantages). How can a traditional CA be configured to use our algorithm?
- [ ] Benefits of using IMEI as an input to the keccak256 algorithm
- [ ] Create an end-to-end diagram that maps the user journey, from the moment they're enrolled to the moment they get a doubly-signed record and start their usage cycle. Identify all the pieces and entities that are involved. What smart contracts do we need? What are the dependencies?
- [ ] For every design choice, identify the limitations and explain why the benefits outweigh them
- [ ] What are the alternatives and analyze them
- [ ] Pick a framework for the prototype
